repository: arcus-azure/arcus.templates
theme: jekyll-theme-slate
logo: https://raw.githubusercontent.com/arcus-azure/arcus/master/media/arcus.png
title: Arcus Templates
description: Azure development in a breeze with our templates
plugins:
  - jemoji
